# Generated by Django 3.0.2 on 2020-06-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200625_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitutude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
