# Generated by Django 3.0.2 on 2020-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200625_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=30, max_digits=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitutude',
            field=models.DecimalField(decimal_places=30, max_digits=30),
        ),
    ]
