# Generated by Django 3.0.2 on 2020-06-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200625_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitutude',
            field=models.FloatField(),
        ),
    ]
