# Generated by Django 3.0.2 on 2020-07-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200625_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
