# Generated by Django 3.0.2 on 2020-07-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_playlistaddedsongs_song_userplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaylist',
            name='playlist_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
