# Generated by Django 3.0.2 on 2020-07-10 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userplaylist_playlist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Userplaylist')),
                ('user_permitted', models.ManyToManyField(related_name='permissionsgiven', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
