# Generated by Django 3.0.2 on 2020-07-12 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_playlistpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistaddedsongs',
            name='playlistsongs',
            field=models.ManyToManyField(related_name='playlistsong', to='api.Song'),
        ),
        migrations.AlterField(
            model_name='playlistpermission',
            name='user_permitted',
            field=models.ManyToManyField(blank=True, null=True, related_name='permissionsgiven', to=settings.AUTH_USER_MODEL),
        ),
    ]
