# Generated by Django 3.0.2 on 2020-07-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200712_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistaddedsongs',
            name='playlist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Userplaylist', unique=True),
        ),
    ]
