# Generated by Django 3.0.2 on 2020-07-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200712_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistaddedsongs',
            name='playlist_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Userplaylist'),
        ),
    ]
